### ISSUE TITLE
Where does one put the Junos installer tarballs?

### ISSUE THREAD

**Issue by wdennis** [consentfactory/ztpgenerator#1]
I see that the rendered configs get put in the `configs` dir; does one put the Junos installer tarballs there as well, or do you intend they get served from another web server somewhere?

**Comment by wdennis** [comment]
Ah, from the rendered `hosts.conf` I see it is looking for them in a subdir named `images`:
```
option ezjunosztp.image-file-name "images/jinstall-ex-2200[...]
```
This dir was not created when I did the project clone; it was probably a empty dir on your original project when you pushed it to GitHub, and hence was not included in the commit. You could create a README file in it (perhaps just saying "PUT IMAGE FILES HERE" or the like), then commit/push that, which would then cause the `images` dir to be created on a clone.

I have created it locally, and put my images in there, so OK now.

**Comment by commitconfirm** [comment]
Correct. That's a mistake on my part.

I'm going to go through my original project files and verify nothing else is missing. 

Thanks for the heads up!

**Comment by commitconfirm** [comment]
Went ahead and created that directory per your suggested. Great idea. 

Thanks again!
